name: Build Docs

on: 
  push:
    branches: 
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2.0.0

    - name: Setup Node
      uses: actions/setup-node@v1.1.0

    - name: Install Dependencies
      run: yarn

    - name: Build Docs
      run: yarn build

    - name: Deploy To Pages
      uses: JamesIves/github-pages-deploy-action@releases/v3
      with:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        BRANCH: gh-pages
        FOLDER: "docs/.vuepress/dist"
