name: Build Docs

on: 
  push:
    branches: 
      - master

jobs:
  build:
    runs-on: ubuntu-16.04

    steps:
    - name: Checkout
      uses: actions/checkout@v2.0.0

    - name: Setup Node
      uses: actions/setup-node@v1.1.0

    - name: Install Dependencies
      run: |
        ls
        yarn
        ls node_modules

    - name: Build Docs
      run: |
        ls
        cd ..
        ls
      working-directory: .

    - name: Deploy To Pages
      env:
        BUILD_DIR: "docs/.vuepress/dist"
      uses: maxheld83/ghpages@v0.2.1
